version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: auth-db
    env_file:
      - ./docker/db.env
    ports:
      - "5432:5432"
    volumes:
        - db-data:/var/lib/postgresql/data
  api:
    build: .
    container_name: auth-api
    env_file:
      - .env
    ports:
      - "8080:8080"
volumes:
    db-data:
