name: Check PRs
on:
  pull_request:
    branches:
      - master
env:
  JAVA_VERSION: 17
  GRADLE_VERSION: 8.6
jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'amazon-corretto'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Lint with Gradle
        run: ./gradlew spotlessCheck
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'amazon-corretto'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Test with Gradle
        run: ./gradlew test
  check:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'amazon-corretto'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Check with Gradle
        run: ./gradlew check
  build:
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'amazon-corretto'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Build with Gradle
        run:  ./gradlew build -x check
