name: Check PRs
on:
  pull_request:
    branches:
      - master
env:
  JAVA_VERSION: 21
  JAVA_DISTRO: 'corretto'
  GRADLE_VERSION: 8.6
  ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  CONTEXT_PATH: ${{ secrets.CONTEXT_PATH }}

permissions:
  checks: write
jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Lint with Gradle
        run: ./gradlew spotlessCheck
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Test with Gradle
        run: ./gradlew test
      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}
      - name: Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: 'build/reports/jacoco/test/jacocoTestReport.xml'
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ github.token }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false
      - name: Add Coverage Job Summary
        run: |
          echo "| Metric              | Value                               |" >> $GITHUB_STEP_SUMMARY
          echo "|:--------------------|-------------------------------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Coverage Percentage | ${{ env.coveragePercentageString }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Covered Lines       | ${{ env.covered_lines }}            |" >> $GITHUB_STEP_SUMMARY
          echo "| Missed Lines        | ${{ env.missed_lines }}             |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Lines         | ${{ env.total_lines }}              |" >> $GITHUB_STEP_SUMMARY

  check:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Check with Gradle
        run: ./gradlew check
  build:
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Build with Gradle
        run: ./gradlew build -x check
